--1
SELECT DELIVERERID, MIN(DATA), MAX(DATA)
FROM PENALTIES
GROUP BY DELIVERERID
HAVING COUNT(*) >= 2;

--2
SELECT P1.DELIVERERID, DATA, AMOUNT
FROM PENALTIES P1
WHERE DATA = (SELECT MAX(DATA)
                FROM PENALTIES P2
                WHERE P2.DELIVERERID = P1.DELIVERERID);
--oppure
SELECT DELIVERERID, DATA, AMOUNT
FROM PENALTIES
WHERE (DATA, DELIVERERID) IN (SELECT MAX(DATA), DELIVERERID
                                FROM PENALTIES
                                GROUP BY DELIVERERID
                                HAVING COUNT(*) >= 1);

--3
SELECT COMPANYID
FROM COMPANYDEL
GROUP BY COMPANYID
HAVING COUNT(*) > (SELECT 0.30*COUNT(*)
                    FROM DELIVERERS);
