--1
SELECT *
FROM DELIVERERS;

--2
SELECT COMPANYID
FROM COMPANIES;

--3
SELECT name, delivererid
FROM DELIVERERS
WHERE NAME LIKE 'B%';

--4
SELECT name, sex, delivererid
FROM DELIVERERS
WHERE phoneno <> '8467' OR phoneno IS NULL;

--5
SELECT DISTINCT name, town
FROM DELIVERERS D, PENALTIES P
WHERE D.DELIVERERID = P.DELIVERERID;
--oppure
SELECT name, town
FROM DELIVERERS
WHERE DELIVERERID IN (SELECT DELIVERERID
                        FROM PENALTIES);

--6
SELECT DISTINCT NAME, INITIALS
FROM DELIVERERS D, PENALTIES P, COMPANIES C
WHERE D.DELIVERERID = P.DELIVERERID AND C.DELIVERERID = D.DELIVERERID
        AND P.DATA > TO_DATE('31/12/1980', 'DD/MM/YYYY')
ORDER BY NAME;
--oppure
SELECT NAME, INITIALS
FROM DELIVERERS
WHERE DELIVERERID IN (SELECT DELIVERERID
                        FROM COMPANIES
                        WHERE DELIVERERID IN (SELECT DELIVERERID
                                                 FROM PENALTIES
                                                 WHERE DATA > TO_DATE('31/12/1980', 'DD/MM/YYYY')))
ORDER BY NAME;

--7
SELECT c.companyid, c.delivererid
FROM COMPANYDEL C, DELIVERERS D
WHERE D.DELIVERERID = C.DELIVERERID
        AND TOWN = 'Stratford'
        AND numcollections >= 2 AND numdeliveries >= 1;
--oppure
SELECT COMPANYID, DELIVERERID
FROM COMPANYDEL
WHERE DELIVERERID IN (SELECT DELIVERERID
                        FROM DELIVERERS
                        WHERE TOWN = 'Stratford')
        AND NUMCOLLECTIONS >=2 AND NUMDELIVERIES >= 1;

--8        
SELECT D.DELIVERERID
FROM DELIVERERS D, COMPANYDEL C, COMPANIES CO
WHERE YEAR_OF_BIRTH > 1962 AND CO.MANDATE = 'first'
        AND D.DELIVERERID = C.DELIVERERID AND CO.COMPANYID = C.COMPANYID
        AND C.NUMDELIVERIES >= 1
ORDER BY D.DELIVERERID DESC;
--oppure
SELECT DELIVERERID
FROM DELIVERERS
WHERE YEAR_OF_BIRTH > 1962
        AND DELIVERERID IN (SELECT DELIVERERID
                            FROM COMPANYDEL
                            WHERE NUMDELIVERIES >=1
                                    AND COMPANYID IN (SELECT COMPANYID
                                                        FROM COMPANIES
                                                        WHERE MANDATE = 'first'))
ORDER BY DELIVERERID DESC;

--9
SELECT NAME
FROM DELIVERERS D, COMPANYDEL C
WHERE D.DELIVERERID = C.DELIVERERID
        AND (TOWN = 'Stratford' OR TOWN = 'Inglewood')
GROUP BY D.DELIVERERID, NAME
HAVING COUNT(*) > 1;
--oppure
SELECT NAME
FROM DELIVERERS
WHERE DELIVERERID IN (SELECT DELIVERERID
                        FROM COMPANYDEL
                        GROUP BY DELIVERERID
                        HAVING COUNT(*) > 1)
        AND (TOWN = 'Stratford' OR TOWN = 'Inglewood');

--10
SELECT D.DELIVERERID, SUM(AMOUNT)
FROM DELIVERERS D, PENALTIES P
WHERE D.TOWN = 'Inglewood' AND D.DELIVERERID = P.DELIVERERID
GROUP BY D.DELIVERERID
HAVING COUNT(*) > 1;
--oppure
SELECT DELIVERERID, SUM(AMOUNT)
FROM PENALTIES
WHERE DELIVERERID IN (SELECT DELIVERERID
                        FROM DELIVERERS
                        WHERE TOWN = 'Inglewood')
GROUP BY DELIVERERID
HAVING COUNT(*) > 1;

--11
SELECT D.NAME, MIN(P.AMOUNT)
FROM DELIVERERS D, PENALTIES P
WHERE D.DELIVERERID = P.DELIVERERID
GROUP BY D.DELIVERERID, NAME
HAVING COUNT(*) >= 2 AND COUNT(*) <= 4;

--12
SELECT SUM(C.NUMDELIVERIES), SUM(NUMCOLLECTIONS)
FROM DELIVERERS D, COMPANYDEL C
WHERE D.DELIVERERID = C.DELIVERERID
        AND D.TOWN <> 'Stratford' AND D.NAME LIKE 'B%';
--oppure
SELECT SUM(NUMDELIVERIES), SUM(NUMCOLLECTIONS)
FROM COMPANYDEL
WHERE DELIVERERID IN (SELECT DELIVERERID
                        FROM DELIVERERS
                        WHERE TOWN <> 'Stratford' AND NAME LIKE 'B%');
