--1
SELECT DELIVERERID, NAME, INITIALS
FROM DELIVERERS
WHERE DELIVERERID NOT IN (SELECT DELIVERERID
                            FROM PENALTIES);

--2
SELECT DELIVERERID
FROM DELIVERERS
WHERE DELIVERERID IN (SELECT DELIVERERID
                        FROM PENALTIES
                        WHERE AMOUNT=25)
        AND DELIVERERID IN (SELECT DELIVERERID
                        FROM PENALTIES
                        WHERE AMOUNT=30);
                        
--3
SELECT DELIVERERID, NAME
FROM DELIVERERS
WHERE DELIVERERID IN (SELECT DELIVERERID
                        FROM PENALTIES
                        GROUP BY DELIVERERID, DATA
                        HAVING COUNT(DATA) > 1);
                        
--4
SELECT DELIVERERID
FROM COMPANYDEL
WHERE NUMDELIVERIES >= 1 OR NUMCOLLECTIONS >= 1
GROUP BY DELIVERERID
HAVING COUNT(*) = (SELECT COUNT(*)
                    FROM COMPANIES);

--5
SELECT DELIVERERID
FROM COMPANYDEL
WHERE COMPANYID IN (SELECT COMPANYID
                        FROM COMPANYDEL
                        WHERE DELIVERERID = 57)
        AND DELIVERERID <> 57;

--6
SELECT P.DELIVERERID, D.NAME
FROM PENALTIES P, DELIVERERS D
WHERE D.DELIVERERID = P.DELIVERERID
        AND DATA >= TO_DATE('01/01/1980', 'DD/MM/YYYY')
        AND DATA <= TO_DATE('31/12/1980', 'DD/MM/YYYY')
GROUP BY P.DELIVERERID, D.NAME
HAVING COUNT(*) > (SELECT COUNT(*)
                    FROM PENALTIES P2
                    WHERE P2.DELIVERERID = P.DELIVERERID
                            AND DATA >= TO_DATE('01/01/1981', 'DD/MM/YYYY')
                             AND DATA <= TO_DATE('31/12/1981', 'DD/MM/YYYY'));
                             
--7
SELECT DELIVERERID
FROM PENALTIES
GROUP BY DELIVERERID
HAVING COUNT(*) = (SELECT MAX(COUNT(*))
                    FROM PENALTIES
                    GROUP BY DELIVERERID);

--8
SELECT DELIVERERID
FROM COMPANYDEL
WHERE COMPANYID IN (SELECT COMPANYID
                    FROM COMPANYDEL
                    WHERE DELIVERERID = 57)
GROUP BY DELIVERERID
HAVING COUNT(*) = (SELECT COUNT(*)
                    FROM COMPANYDEL
                    WHERE DELIVERERID = 57)
        AND DELIVERERID <> 57;

--9
SELECT DELIVERERID
FROM COMPANYDEL
WHERE DELIVERERID NOT IN (SELECT DELIVERERID
                            FROM COMPANYDEL
                            WHERE COMPANYID NOT IN (SELECT COMPANYID
                                                    FROM COMPANYDEL
                                                     WHERE DELIVERERID = 57))
        AND DELIVERERID <> 57;

--10
SELECT DELIVERERID
FROM COMPANYDEL
WHERE DELIVERERID NOT IN (SELECT DELIVERERID
                            FROM COMPANYDEL
                            WHERE COMPANYID NOT IN (SELECT COMPANYID
                                                    FROM COMPANYDEL
                                                     WHERE DELIVERERID = 57))
        AND DELIVERERID <> 57
GROUP BY DELIVERERID
HAVING COUNT(*) = (SELECT COUNT(*)
                    FROM COMPANYDEL
                    WHERE DELIVERERID = 57);